# Generated by Django 3.1.2 on 2020-10-31 14:58

from django.db import migrations, models
import martor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('markdownpages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NaturePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('body', martor.models.MartorField()),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField()),
                ('tags', models.ManyToManyField(to='markdownpages.Tag')),
            ],
        ),
    ]
