# Generated by Django 3.1.2 on 2020-11-01 16:59

from django.db import migrations, models
import martor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_kapnoc', '0002_auto_20201101_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='NaturePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', martor.models.MartorField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
                ('tags', models.ManyToManyField(to='django_kapnoc.Tag')),
            ],
        ),
    ]
