# Generated by Django 3.1.2 on 2020-11-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nature', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='naturepage',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
