# Generated by Django 3.1.2 on 2020-11-05 19:32

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('nature', '0002_naturepage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='naturepage',
            name='body_vo',
            field=martor.models.MartorField(default=''),
            preserve_default=False,
        ),
    ]
